version: "0.0.1"
services:
  database:
    container_name: mysql_db
    image: mysql/mysql-server:latest
    #restart: unless-stopped
    env_file:
      - ./database.env
    environment:
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - backend-net

  application:
    container_name: was
    restart: on-failure
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./application.env
    depends_on:
      - database
    networks:
      - backend-net

  web:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - database
    networks:
      - backend-net


networks:
  backend-net:
