version: "0.0.1"
services:
  database:
    container_name: mysql_db
    image: mysql/mysql-server:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shared_backend
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - backend-net

  application:
    container_name: was
    image: cinnamonlol/pw_manager:0.0.3
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/shared_backend?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_JWT_SECRET: "12312341562346231231231252462346124152463643641234123412513523654523"
      naver-client-id: "m_pT5WYQo6xw4gBMXAhM"
      naver-client-secret: "Pzo483lfaJ"
      naver-redirect-uri: "http://172.30.1.3:8080/login/oauth2/code/naver"


    depends_on:
      - database
    networks:
      - backend-net

  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - database
    networks:
      - backend-net


networks:
  backend-net:
